// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALQ1JftBW-GeHO1d_UcuyNEVD7tt0P3sY',
    appId: '1:899219304290:web:d52a4297fe8cb62b3dc63b',
    messagingSenderId: '899219304290',
    projectId: 'mynotes-crud',
    authDomain: 'mynotes-crud.firebaseapp.com',
    storageBucket: 'mynotes-crud.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArE_q-gGZwf3tTbI3zzjgFdnDbkJ1eNzI',
    appId: '1:899219304290:android:9cf0f9928087b39f3dc63b',
    messagingSenderId: '899219304290',
    projectId: 'mynotes-crud',
    storageBucket: 'mynotes-crud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQaJRlj0-SQuN_z-bO9bH5y79PqHk8RXM',
    appId: '1:899219304290:ios:a3b0ac0c95073f123dc63b',
    messagingSenderId: '899219304290',
    projectId: 'mynotes-crud',
    storageBucket: 'mynotes-crud.appspot.com',
    iosClientId: '899219304290-osbk7ln27mijvirf98uq5db8injt3rf4.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudNots',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQaJRlj0-SQuN_z-bO9bH5y79PqHk8RXM',
    appId: '1:899219304290:ios:a3b0ac0c95073f123dc63b',
    messagingSenderId: '899219304290',
    projectId: 'mynotes-crud',
    storageBucket: 'mynotes-crud.appspot.com',
    iosClientId: '899219304290-osbk7ln27mijvirf98uq5db8injt3rf4.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudNots',
  );
}
